name: Build and send diploma thesis

on: 
  push:
    branches:
      - wolf
    paths:
      - Diplomarbeit/**
  workflow_dispatch:

jobs:
  build-send:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build And Send Diploma Thesis (template action)
        uses: ./Diplomarbeit/da-base-template
        with:
          thesis-path: Diplomarbeit
          dockerhub-username: bytebang
          dockerhub-repository: htlle-da-builder
